//
// Created by wyz on 2021/8/23.
//

#ifndef MULTIVOLUMERENDER_SINGLESCALARFIELDRENDER_HPP
#define MULTIVOLUMERENDER_SINGLESCALARFIELDRENDER_HPP

class SingleScalarFieldRender{

};

#endif //MULTIVOLUMERENDER_SINGLESCALARFIELDRENDER_HPP
