//
// Created by wyz on 2021/8/23.
//

#ifndef MULTIVOLUMERENDER_SCALARANDVECTORFILEDRENDER_HPP
#define MULTIVOLUMERENDER_SCALARANDVECTORFILEDRENDER_HPP


class ScalarAndVectorFiledRender {

};


#endif //MULTIVOLUMERENDER_SCALARANDVECTORFILEDRENDER_HPP
