//
// Created by wyz on 2021/8/23.
//

#ifndef MULTIVOLUMERENDER_MULTISCALARFIELDRENDER_HPP
#define MULTIVOLUMERENDER_MULTISCALARFIELDRENDER_HPP


class MultiScalarFieldRender {

};


#endif //MULTIVOLUMERENDER_MULTISCALARFIELDRENDER_HPP
