//
// Created by wyz on 2021/8/23.
//

#ifndef MULTIVOLUMERENDER_MULTIISOSURFACERENDER_HPP
#define MULTIVOLUMERENDER_MULTIISOSURFACERENDER_HPP


class MultiIsoSurfaceRender {

};


#endif //MULTIVOLUMERENDER_MULTIISOSURFACERENDER_HPP
